-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 09:32:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kenefbet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kenefbet
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `kenefbet` DEFAULT CHARACTER SET utf8 ;
USE `kenefbet` ;

-- -----------------------------------------------------
-- Table `kenefbet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kenefbet`.`users` (
  `idusers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `egn` VARCHAR(10) NOT NULL,
  `bank_info` VARCHAR(34) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kenefbet`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kenefbet`.`games` (
  `idgames` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `kind` VARCHAR(45) NOT NULL,
  `chance` DOUBLE NOT NULL,
  `jackpot_chance` DOUBLE NOT NULL,
  `bonus` DOUBLE NOT NULL,
  `jackpot` DOUBLE NOT NULL,
  `date_added` DATE NOT NULL,
  PRIMARY KEY (`idgames`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kenefbet`.`banlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kenefbet`.`banlist` (
  `idbanlist` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idbanlist`, `users_idusers`),
  INDEX `fk_banlist_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_banlist_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `kenefbet`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kenefbet`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kenefbet`.`promotions` (
  `idpromotions` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `games_idgames` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpromotions`, `games_idgames`),
  INDEX `fk_promotions_games1_idx` (`games_idgames` ASC),
  CONSTRAINT `fk_promotions_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `kenefbet`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kenefbet`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kenefbet`.`transaction` (
  `idtransaction` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `size` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `fk_transaction_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_transaction_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `kenefbet`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kenefbet`.`most_played`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kenefbet`.`most_played` (
  `idtable1` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `games_idgames` INT UNSIGNED NOT NULL,
  `traffic` INT NULL,
  PRIMARY KEY (`idtable1`, `games_idgames`),
  INDEX `fk_most_played_games1_idx` (`games_idgames` ASC),
  CONSTRAINT `fk_most_played_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `kenefbet`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
